USE CHANUARAIYA
GO
CREATE TABLE Users(
    UserId VARCHAR(255) NOT NULL PRIMARY KEY,
    Username VARCHAR(255) NOT NULL,
    Email VARCHAR(255) UNIQUE NOT NULL,
    Role VARCHAR(255) NOT NULL DEFAULT 'User',
    PasswordHash VARCHAR(255) NOT NULL,
    CreatedAt DATETIME DEFAULT GETDATE()
)
GO
USE CHANUARAIYA
CREATE TABLE Topics(
    TopicId VARCHAR(255) NOT NULL PRIMARY KEY,
    Title VARCHAR(350) NOT NULL,
    Context VARCHAR(2500) NULL,
    CreatedAt DATETIME DEFAULT GETDATE()
)
GO
CREATE TABLE Views(
    ViewId VARCHAR(255) NOT NULL PRIMARY KEY,
    Opinion VARCHAR(1600) NOT NULL,
    UserId VARCHAR(255) FOREIGN KEY REFERENCES Users(UserId),
    TopicId VARCHAR(255) NOT NULL FOREIGN KEY REFERENCES Topics(TopicId) ON DELETE CASCADE
)
USE CHANUARAIYA
DROP TABLE Views
DROP TABLE Topics